version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: network_inventory
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - '8080:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=django_network_inventory.settings
      - POSTGRES_PASSWORD=admin123  
    volumes:
      - ./django_network_inventory:/inventory
volumes:
  postgres_data:
  pgadmin_data:
